"""initial schema

Revision ID: 638214c31b7d
Revises: 
Create Date: 2026-06-16 14:20:49.503712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638214c31b7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('join_code', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_join_code'), 'classrooms', ['join_code'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=50), nullable=False),
    sa.Column('personal_code', sa.String(length=8), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_personal_code'), 'students', ['personal_code'], unique=True)
    op.create_table('student_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.SmallInteger(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('unlock_requested', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'activity', name='uq_student_activity')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('player', sa.SmallInteger(), nullable=False),
    sa.Column('roll_number', sa.SmallInteger(), nullable=False),
    sa.Column('dice_count', sa.SmallInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['student_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('student_datasets')
    op.drop_index(op.f('ix_students_personal_code'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_classrooms_join_code'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
